variables:
  VERSION: 1.0.${CI_PIPELINE_ID}

stages:
   - build
   - docker-build
   - release

build-code-job:
  stage: build
  image: golang:1.17
  variables:
    GOPATH: $CI_PROJECT_DIR/backend/.go
    CGO_ENABLED: "0"
    GIT_DEPTH: "0"
  before_script:
    - mkdir -p backend/.go
  script:
    - cd backend/cmd/api/
    - go build .
    - mkdir -p $CI_PROJECT_DIR/momo-store-${VERSION}
    - mv api $CI_PROJECT_DIR/momo-store-${VERSION}/
  cache:
    key: $CI_COMMIT_REF_SLUG
    paths:
      - backend/.go/pkg/mod/
  artifacts:
    paths:
      - momo-store-${VERSION}/api

# НОВАЯ JOB: Сборка Docker-образа
build-docker-image:
  stage: docker-build
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  dependencies:
    - build-code-job
  before_script: | 
      echo "${CI_PROJECT_DIR}\backend\Dockerfile"
  script:
    - |
      /kaniko/executor \
        --context "${CI_PROJECT_DIR}" \
        --dockerfile "${CI_PROJECT_DIR}\backend\Dockerfile" \
        --destination "${CI_REGISTRY_IMAGE}/momo-backend:${CI_COMMIT_SHORT_SHA}" \
        --destination "${CI_REGISTRY_IMAGE}/momo-backend:${VERSION}" \
        --cache=true
    - echo "Docker image built and pushed successfully"
  only:
    changes:
      - backend/**/*

release:
  stage: release
  variables:
    GIT_STRATEGY: none
  image:
    name: gcr.io/go-containerregistry/crane:debug
    entrypoint: [ "" ]
  cache: [ ]
  dependencies:
    - build-docker-image  # Важно: зависимость от сборки образа
  before_script:
    - crane auth login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - crane tag $CI_REGISTRY_IMAGE/momo-backend:$CI_COMMIT_SHORT_SHA $VERSION
    - echo "Successfully tagged $CI_REGISTRY_IMAGE/momo-backend:$VERSION"
  only:
    changes:
      - backend/**/*