apiVersion: apps/v1
kind: Deployment
metadata:
  name: momo-backend
  labels:
    app: momo-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: momo-backend
  template:
    metadata:
      labels:
        app: momo-backend
    spec:
      containers:
      - name: backend
        image: gitlab.praktikum-services.ru:5050/std-int-005-013/varenikilife/momo-backend:1.0.${CI_PIPELINE_ID}
        ports:
        - containerPort: 8080
        env:
        - name: ENVIRONMENT
          value: "production"