apiVersion: apps/v1
kind: Deployment
metadata:
  name: momo-frontend
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: momo-frontend
  template:
    metadata:
      labels:
        app: momo-frontend
    spec:
      containers:
      - name: frontend
        image: gitlab.praktikum-services.ru:5050/std-int-005-013/varenikilife/momo-frontend:latest
        ports:
        - containerPort: 80
        volumeMounts:
        - name: nginx-config
          mountPath: /etc/nginx/conf.d/default.conf
          subPath: default.conf
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "200m" 
            memory: "256Mi"
      volumes:
        - name: nginx-conf
          configMap:
            name: nginx-conf
            items:
              - key: nginx.conf
                path: nginx.conf
      imagePullSecrets:
      - name: gitlab-registry